### ISSUE TITLE
The graphical installer does not start in the 0.17 alpha

### ISSUE THREAD

**Issue by marek-lach** [gobolinux/Installer#13]
Clicking on the installer application after running the graphical interface `startx`, does NOT end-up launching the installer at all.

**Comment by lucasvr** [comment]
Thanks for the heads up. Yes, this is a known issue -- the graphical installer is based on our AbsTK toolkit, which handles both Ncurses and Qt 3. We don't want to ship with Qt 3, so we're gonna have to port AbsTK to Qt 4 (or 5). I hope that I'll have that sorted out in the beta release.
