### ISSUE TITLE
Fails to install on MMC device

### ISSUE THREAD

**Issue by lucasvr** [gobolinux/Installer#16]
As reported by Jorge Huicochea on Facebook, the following partition table configuration is not recognized by the Installer:

![image](https://user-images.githubusercontent.com/11136056/83364174-a56b5f80-a375-11ea-82e6-0bf3569511f2.png)

**Comment by thebitstick** [comment]
Seems to be a problem with this line?
https://github.com/gobolinux/Installer/blob/master/bin/GoboLinuxInstaller#L51

**Comment by thebitstick** [comment]
Could it possibly related to this?
https://github.com/gobolinux/Installer/blob/6f56f9638a64cc1ef2a6b896f8cccaef04a6cdb3/bin/GoboLinuxInstaller#L99
It has nvme in it's name?

**Comment by lucasvr** [comment]
NVMe was not originally supported, so that regex was introduced to allow strings such as nvme0n1p1 to be recognized as a valid partition device. The fix to support MMC is going to be similar to that one.

**Comment by thebitstick** [comment]
Actually, partitionsList would contain the mmc partitions but discsList removes it
https://github.com/gobolinux/Installer/blob/6f56f9638a64cc1ef2a6b896f8cccaef04a6cdb3/bin/GoboLinuxInstaller#L104
https://github.com/gobolinux/Installer/blob/6f56f9638a64cc1ef2a6b896f8cccaef04a6cdb3/bin/GoboLinuxInstaller#L106

**Comment by thebitstick** [comment]
```python
dmmcblk = re.compile(r'\b[m]+[m]+[c]+[b]+[l]+[k]+[0-9]+\b')
```
Seems to work, but that's very ugly, so:
```python
dmmcblk = re.compile(r'\b[a-z]+[a-z]+[a-z]+[a-z]+[a-z]+[a-z]+[0-9]+\b')
```
also works too.

But testing it out, it still doesn't fix the Installer complaining. 🤔

**Comment by thebitstick** [comment]
Huh.
I think I found a bug in partinfo.
Running `partinfo --flags` gives a fatal error about a strange partition on my Surface device.
It's an mmc partition that is read-only, and that I can't access. It's not a problem on other installers.
If I bypass getEFIPartitionsList and set it to my mmc device, I can install GoboLinux on my device.
EDIT: It attempts to install, but fails.
EDIT: Nevermind I symlink'd mmcblk1 to sdb to attempt to go around the installer before. Works now.

**Comment by thebitstick** [comment]
https://github.com/gobolinux/Installer/commit/9e01b96d103e8c9ba2a71ee7373bb68cf5383ec3 is what I edited for the installer to let me select the correct root.
`partinfo` is still a problem, however.

**Comment by hishamhm** [comment]
@lucasvr I wonder if we should add a textbox in the Installer ("alternatively, type in your partition name here if it does not automatically appear in the list") to make the Installer more future-proof? These things have hit us several times over the... decades :)

**Comment by lucasvr** [comment]
@hishamhm yes, that's a good solution to the problem (besides fixing the problems with partinfo). I'll look into fixing these later this week.

**Comment by thebitstick** [comment]
Pull #17 fixes eMMC storage but it still doesn't fix partinfo :/

**Comment by lucasvr** [comment]
Could you paste the output of the partinfo command that fails? Also, could you output what `parted -l` says?

**Comment by thebitstick** [comment]
Here's partinfo: ![image](https://user-images.githubusercontent.com/13919134/84964205-2003e100-b0d1-11ea-8ddc-b2a6ccc2102d.png)

**Comment by thebitstick** [comment]
Here's parted: ![image-2](https://user-images.githubusercontent.com/13919134/84964405-a6202780-b0d1-11ea-9c81-8df446955b21.png)

**Comment by lucasvr** [comment]
I've just pushed a fix to ConfigTools that should fix this. Could you try it and let me know if the problem still persists?

**Comment by thebitstick** [comment]
To be honest, I haven't touched my Surface device much, and I've found that Git somehow refuses to retrieve from Github when trying to compile ConfigTools.
I'll have to figure this out first...

**Comment by lucasvr** [comment]
The issue with git is a known one. You just have to [bring the loopback interface up](https://github.com/gobolinux/Documentation/wiki/GoboLinux-017-Known-Issues-and-Fixes) to fix it. Please let me know the outcome when you have a chance.

**Comment by thebitstick** [comment]
Oh.
Well at least it doesn't crash! And $? is 0, so it wouldn't kill the installer.
![image-3](https://user-images.githubusercontent.com/13919134/85033153-3d26c700-b146-11ea-893e-fa4bbe871973.png)

**Comment by lucasvr** [comment]
Great, thanks for testing! Out of curiosity, are the error messages echoed to stdout or stderr? You can test that by running `partinfo --flags 2> /dev/null`

**Comment by thebitstick** [comment]
With that, they are completely out of stdout. So this is probably the output the installer would get!

**Comment by lucasvr** [comment]
Awesome! I'm closing this issue now. Thanks for your help on this one!
