### ISSUE TITLE
git-clone fails in fresh install to QEMU image

### ISSUE THREAD

**Issue by bolangi** [gobolinux/Installer#18]
Dear Maintainers,

When I run the Gobo 017 ISO under QEMU, Compile and git-clone proceed as normal (until disk space runs out). After installing Gobo 017 to a QEMU image and rebooting, git-clone fails with "getaddrinfo() thread fails to start".  Network access (for example "wget yahoo.com") works fine, and the firewall is disabled. 

Fresh install started as:

 qemu-system-x86_64 \
-enable-kvm \
-show-cursor \
-boot c \
-m 768 \
-cpu host \
-daemonize \
-vga vmware \
-soundhw ac97 \
-rtc base=utc \
-usb \
-device usb-mouse \
-hda gobo17.img

ISO started identically, except

-cdrom GoboLinux-017-x86_64.iso

I also tried various -smp settings to no effect.

**Comment by lucasvr** [comment]
Hi @bolangi. This is a known problem with 017. Please take a look at https://github.com/gobolinux/Documentation/wiki/GoboLinux-017-Known-Issues-and-Fixes for the fix for this and other issues identified with this particular release. Please let us know if the workaround fixes it for you.

**Comment by bolangi** [comment]
On Sun, Jan 03, 2021 at 06:05:36PM -0800, Lucas C. Villa Real wrote:

> Hi @bolangi. This is a known problem with 017. Please take
> a look at
> https://github.com/gobolinux/Documentation/wiki/GoboLinux-017-Known-Issues-and-Fixes
> for the fix for this and other issues identified with this
> particular release. Please let us know if the workaround
> fixes it for you.

Thank you, Lucas. Somehow I missed the link to the Known
Issues page you put in the Downloads page. 



-- 
Joel Roth

**Comment by lucasvr** [comment]
No worries. I'm closing this one now. Best regards!
