### ISSUE TITLE
Line 28: 16519 Bus error - GoboLinuxInstaller install $args

### ISSUE THREAD

**Issue by code-hunger** [gobolinux/Installer#2]
I get this error after running the graphical installer. `echo $?` returns `0`. 
After filling all fields and clicking "Finish" the window just closes with no messages. I found the error after running `Installer` from the terminal.

**Update**
Ok so I rebooted and ran `Installer` from the tty prompt. It finished successfully.
The only problem I had before launching the new system was that `shutdown now` froze and I had to force it manually.

**Comment by lucasvr** [comment]
Bus errors indicate you have a problem with the storage device where you copied the ISO to. This is typical of USB devices which are starting to wear, loose connectors, broken USB cables, scratched DVDs, and so on.

**Comment by lucasvr** [comment]
As for shutdown not shutting the machine down, you have to pass "-h" to ask the machine to halt, as in `shutdown -h now`. I am closing this issue now since those are not really defects on the Installer code base.
