### ISSUE TITLE
Console-mode installation fails with LANG=de_DE.UTF-8

### ISSUE THREAD

**Issue by lucasvr** [gobolinux/Installer#3]
As reported by Rudy R., Installer crashes right after the password is entered on the password dialog. The problem does not happen with the graphical installer.
![screenshot](https://cloud.githubusercontent.com/assets/11136056/21575204/45f4103a-ceec-11e6-8f86-94588bf1e3aa.png)

**Comment by hishamhm** [comment]
I'm investigating this bug. We switched to UTF-8 by default in the ISO, and Python Unicode handling can be pretty annoying: https://pythonhosted.org/kitchen/unicode-frustrations.html

**Comment by hishamhm** [comment]
I'm investigating this bug. We switched to UTF-8 by default in the ISO, and Python Unicode handling can be pretty annoying: https://pythonhosted.org/kitchen/unicode-frustrations.html

**Comment by lucasvr** [comment]
Fixed by commits d2dcd6a7cb5cda8b9023bc78ea864d80587866de and https://github.com/gobolinux/AbsTK/commit/d2dcd6a7cb5cda8b9023bc78ea864d80587866de
