### ISSUE TITLE
Install script errors in UEFI mode

### ISSUE THREAD

**Issue by taylorstutts** [gobolinux/Installer#7]
Hi,

I installed the alpha and the beta of GoboLinux 016.01 in VirtualBox in 64-bit UEFI mode and there were several errors. I was able to fix these with the following edits to the install scripts.

1. When the install script is run, it crashes with message "bootloaderTarget referenced before assignment". I edited the main install script and moved the assignment of bootloaderTarget (line 1210) to right before the first time it's used, when generating fstab (line 1092).

2. In `createEFIConfig()`, it errors when changing directory to `efidir` (line 268) if it does not already exist, so I put `if not os.path.exists(efidir): os.makedirs(efidir)` right before the `chdir()`.

3. I don't recall the exact error message but in the alpha the shell command `udevinfo` throws (called from GenFstab script). I am not very familiar with the udev commands and after some research it looks like `udevinfo --query=env` was deprecated for `udevadm info --query=property`.  See [comment 7 on this old redhat bug](https://bugzilla.redhat.com/show_bug.cgi?id=644330#c7). The beta installer has `udevadm` instead of `udevinfo` but still has `--query=env`. As far as I can tell this is not valid for `udevinfo` and it should be `--query=property`.

4. After I got all the above sorted out, the installer works, but drops to a grub prompt on boot. [These GoboLinux troubleshooting instructions for UEFI mode](https://github.com/gobolinux/Documentation/wiki/Installing-to-external-storage-devices) fixed this problem (for future reference, append `rootwait` to the kernel line in grub-efi.cfg and rerun `grub-mkstandalone-efi`). I'm not familiar enough with grub and efi to further diagnose this. Is there any way to anticipate this situation and update the installer to handle it?

**Comment by lucasvr** [comment]
Hi! Thanks a lot for the detailed report.

Regarding (1) and (2), I will fix them this week before rolling out a new ISO.  I have the impression that --query=env worked for me on the Live environment, but I will double check that. It could be that the option still works for backwards compatibility reasons. In any case, --query=property seems to be the right argument indeed.

The rootwait argument from (4) should have been applied everywhere last time I touched the code, but it looks like it has not. I will double check the code base and will make sure that one is fixed too.

**Comment by lucasvr** [comment]
The reported problems should be all fixed now. Also, I have just checked and eudev handles both --query=property and --query=env:
```
        if (streq(optarg, "property") || streq(optarg, "env"))
                query = QUERY_PROPERTY;
```
The next release of ConfigTools will ship with --query=property for the sake of conformity with Eudev's documentation.
