### ISSUE TITLE
umount hdd before invoking mke2fs

### ISSUE THREAD

**Issue by ghost** [gobolinux/Installer#9]
Slight inconvenience:

"Formatting root partition sda1"

But it was mounted still; I manually mounted it.

Next messages are:

mke2fs 1.43.3

/dev/sda1 is mounted; will not make a filesystem here!

Suggestion to solve this:

- Have the script check if there is something mounted, if the target is mounted, perhaps first umount it. I think otherwise mke2fs would fail.

**Comment by lucasvr** [comment]
It won't be possible to unmount it in a few circumstances (for instance, if there's an active shell whose current directory is in the same partition chosen to be formatted), and there are several reasons why the filesystem is mounted. I'd prefer to let the user handle the situation (as the code currently does).
